[project]
name = "transcribe"
version = "0.1.0"
description = "A command-line tool to transcribe audio files using OpenAI's Whisper model"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.64.0",
    "python-dotenv>=1.0.1",
]
